### ISSUE TITLE
Volume Bug

### ISSUE THREAD

**Issue by Nicky203** [EmreFnfGithub/StenEngine-public#2]
I downloaded the engine and tries to open it, but the result is unbelieveable.
![Screenshot (6)](https://user-images.githubusercontent.com/107852432/174920097-d61e3913-9f6b-4a7f-9bd2-5c8b242798a0.png)
This image is a proof that whatever I do, it won't stop the 'beeping' spam.

**Comment by EmreFnfGithub** [comment]
### Enter the settings, then enter the real options, press edit keybindings, then change the volume up setting and volume down setting
